name: "CI/CD Pipeline"

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - images/**
      - README.md
      - .gitignore

jobs:
  build-and-push:
    name: 🔨 Build and push
    runs-on: self-hosted
    permissions:
      packages: write
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
      - name: 📐 Setup AWS CLI
        uses: ./.github/actions/setup-ecr
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
      - name: 🚧 Build docker image
        run: |
          docker build -t ${{ vars.AWS_ECR_REPOSITORY_NAME }} .
          docker tag ${{ vars.AWS_ECR_REPOSITORY_NAME }} ${{ vars.AWS_ECR_REGISTRY }}/${{ vars.AWS_ECR_REPOSITORY_NAME }}:${{ vars.VERSION }}
      - name: 🎯 Push docker image
        run: |
          docker push ${{ vars.AWS_ECR_REGISTRY }}/${{ vars.AWS_ECR_REPOSITORY_NAME }}:${{ vars.VERSION }}
      - name: 🕔 Push latest tag
        if: ${{ github.ref_name == 'develop' }}
        run: |
          docker tag ${{ vars.AWS_ECR_REPOSITORY_NAME }} ${{ vars.AWS_ECR_REGISTRY }}/${{ vars.AWS_ECR_REPOSITORY_NAME }}:latest
          docker push ${{ vars.AWS_ECR_REGISTRY }}/${{ vars.AWS_ECR_REPOSITORY_NAME }}:latest
      - name: 🐙 Push to GHCR
        # if: ${{ github.ref_name == 'main' }}
        run: |
          echo "🔑 Logging into ghcr.io"
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

          echo "🧩 Preparing image name"
          GITHUB_REPOSITORY=${{ github.repository }}
          GHCR_REPO=ghcr.io/${GITHUB_REPOSITORY@L}
          echo "Registry: $GHCR_REPO"

          echo "🚀 Pushing to ghcr.io"
          docker tag ${{ vars.AWS_ECR_REPOSITORY_NAME }} $GHCR_REPO:latest
          docker push $GHCR_REPO:latest
          docker tag ${{ vars.AWS_ECR_REPOSITORY_NAME }} $GHCR_REPO:${{ vars.VERSION }}
          docker push $GHCR_REPO:${{ vars.VERSION }}
  deploy:
    runs-on: self-hosted
    if: false
    needs: build-and-push
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
      - name: 📐 Setup AWS CLI
        uses: ./.github/actions/setup-ecr
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
      - name:
        run: |
          aws ecs update-service --cluster $CD_AWS_ECS_CLUSTER --service $CD_AWS_ECS_SERVICE --force-new-deployment
  create-release:
    name: Create GitHub Release
    if: ${{ github.ref_name == 'main' }}
    runs-on: self-hosted
    permissions:
      contents: write
    needs: build-and-push
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
      - name: 🪢 Setup git
        run: |
          git config --global user.name "CI/CD Pipeline"
          git config --global user.email "contact@nevah5.dev"
      - name: 🏷️ Create tag
        run: |
          git tag -a ${{ vars.VERSION }} -m "Version ${{ vars.VERSION }}"
          git push --tags
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ vars.VERSION }}
          name: Version ${{ vars.VERSION }}
          generateReleaseNotes: true
